# Site settings
title: History Ignored
email: historyignored@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site to articulate history that has been ignored or avoided.
  Some history secrets have been left out of conventional history, and I would like
  to display some of those hidden details. This is not a site for conspiracies, but rather a 
  site for historical facts that have been avoided. When you are finished reading, you can
  come to your own conclusions as to why this information has been witheld from conventional history.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://historyignored.com" # the base hostname & protocol for your site
twitter_username: historyignored
github_username:  historyignored

# Build settings
markdown: kramdown
